# Tüm hedefleri derle ve çalıştırılabilir dosya oluştur
all:
	g++ -c Vector.cpp
	g++ -c Matrix.cpp
	g++ -c SquareMatrix.cpp
	g++ -c TriangleMatrix.cpp
	g++ -c Complex.cpp
	g++ -c Imaginary.cpp
	g++ -c IdentityMatrix.cpp
	g++ -c main.cpp
	g++ -o Proje2.exe Vector.o Matrix.o SquareMatrix.o TriangleMatrix.o Complex.o Imaginary.o IdentityMatrix.o main.o

# Temizleme
clean:
	del Proje2.exe Vector.o Matrix.o SquareMatrix.o TriangleMatrix.o Complex.o Imaginary.o IdentityMatrix.o main.o
